name: Python Code Checker

# 1. When should this run? (When we push code)
on:
  push:
    branches:
      - main
      
jobs:
  check-my-code:
    # 2. What computer should it run on?
    runs-on: ubuntu-latest

    steps:
      # 3. Pull the code from GitHub onto the robot's computer
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      # 4. Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 5. Run the Linter (The Spell-Checker)
      - name: Run Lint Check
        run: |
          pip install flake8
          flake8 .
